name: CI
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup Node.js 16'
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Node dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
